# Created with YamlCreate.ps1 v2.2.1 using InputObject 🤖 $debug=QUSU.CRLF.7-2-10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: lencx.ChatGPT
PackageVersion: 0.11.1
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2023-03-04
AppsAndFeaturesEntries:
- ProductCode: '{750B7666-616B-4F93-9EFF-4CD8F2D6BBA1}'
  UpgradeCode: '{1A917CA9-57E7-5A87-88B1-686A85ACB29A}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lencx/ChatGPT/releases/download/v0.11.1/ChatGPT_0.11.1_windows_x86_64.msi
  InstallerSha256: FC1E1C107CE5ABED0793C1FDA89BAA841BB52E431FA2C3BB5A621B9AB249C37C
  ProductCode: '{13B71854-7929-4C7A-891F-23A963C90191}'
ManifestType: installer
ManifestVersion: 1.2.0
